### ISSUE TITLE
v8 upgrade

### ISSUE THREAD

**Issue by robblehead** [ShepherdDev/digital-signage#1]
Following update screens are blank.

We are not using IP and only browsing to the IP address.

**Comment by cabal95** [comment]
Hi Rob

Do you know which Beta you are using? There was a core bug in 8.0 that should have been fixed in 8.1 beta, but that was just released yesterday so I haven’t had a chance to see if that did indeed fix the problem yet.

**Comment by robblehead** [comment]
8.0 I haven’t tested it with 8.1 but should have the chance to do that tomorrow

[https://ecemailsignatures.blob.core.windows.net/ecemailsignatures/Rob.png]

**Comment by cabal95** [comment]
I was able to do to initial testing against 8.1 and it seems to be working correctly again.
