### ISSUE TITLE
Issue: Stuck in content channel when all slides have expired

### ISSUE THREAD

**Issue by edcylam** [ShepherdDev/digital-signage#2]
When all slides in a content channel have expired. the digital signage doesn't fall back to the next lower priority content channel for the display. It leaves the screen black.

**Comment by cabal95** [comment]
The schedule defines what content channel to display regardless of what is in it. It would be very correct to have a mid week schedule that normally shows black so that people can schedule mid week slides that only show up for a couple days and then go back to black.

**Comment by edcylam** [comment]
Makes sense. Thanks for your explanation.
<http://www.venturechristian.org/>
*Edmund*Lam
PROJECT MANAGER
edmund@venture.cc | 408.997.4600
*16845 Hicks Road, Los Gatos, CA 95032
<https://www.google.com/maps/place/16845+Hicks+Rd,+Los+Gatos,+CA+95032/data=!4m2!3m1!1s0x808e36b3fcbbf1c9:0x1d7da23ee96c622?sa=X&ved=0ahUKEwjwtMDK-qrOAhUMwmMKHW8vDNIQ8gEIHDAA>*
