### ISSUE TITLE
Can't add feedback for installed digital-signage plug-in 

### ISSUE THREAD

**Issue by ElimAdmin** [ShepherdDev/digital-signage#5]
**Update: skip to the UPDATE below before reading all this.**

Hello.  I successfully installed digital-signage and all was working fine.  Great app, and immediately solved the problem of communicating to screens for us.  Thank you.

To solve another problem I renamed my rock web directory as porirua.elim.org.nz.bak, and restored porirua.elim.org.nz from a recent backup.  As a result I did not have digital-signage working.  So I restored porirua.elim.org.nz from porirua.elim.org.nz.bak.

The digital sign is working again at www.porirua.elim.org.nz/digitalsign/4.

But the plugin is not listed on the installed plug-ins page (Home > Admin Tools > Installed Plug-ins).  Should it be?

I tried to go to the Shop page for the plug-ing to add a review.  It shows as being 'installed' but when I go to add a review I get an error message that tells me 'we can't find any evidence you have installed this plug-in.'

I'm wondering if I've messed something up by restoring to an older version of the web page directory and have lost a link somewhere to the fact that the plug-in is installed?  Or if it is correct that the Plug-in does not list on the plug-ins page, and the fact that the Rate page can't find that it is downloaded is a different problem?

Thoughts?  Advice?
![signage1](https://user-images.githubusercontent.com/4658177/62748586-0ce2a800-ba0e-11e9-9089-782910c73a69.jpg)
![signage2](https://user-images.githubusercontent.com/4658177/62748592-10762f00-ba0e-11e9-8082-a10a70d3f118.jpg)
![signage3](https://user-images.githubusercontent.com/4658177/62748598-123ff280-ba0e-11e9-91f2-7192a5902de9.jpg)
![signage4](https://user-images.githubusercontent.com/4658177/62748730-91352b00-ba0e-11e9-98da-90b22584c38d.jpg)
![signage5](https://user-images.githubusercontent.com/4658177/62748813-e2451f00-ba0e-11e9-92a0-75d872671726.jpg)

**Comment by ElimAdmin** [comment]
UPDATE:  The error message on Rock is incorrect.  It was because I was not logged onto the Rock Community site that it gave that error message.  

I have raised this as a Rock issue.   https://github.com/SparkDevNetwork/Rock/issues/3849

**Can you just confirm that the plug-in should not list on the Installed plug-ins page?**
Thanks

**Comment by cabal95** [comment]
Correct. The Installed Plugins page doesn't list all installed plugins. It is simply a place that plugins should put their own custom pages, if any. In this case, the digital sign plugin doesn't have any custom pages for you to interact with so nothing is added to that section.

The page name `Installed Plugins` made sense at the time, but in hindsight I think everybody agrees it should have had a slightly differently name.
