### ISSUE TITLE
[EN] Allow for Slide specific times on Rock digital-sign plug in

### ISSUE THREAD

**Issue by ElimAdmin** [ShepherdDev/digital-signage#6]
Enhancement Suggestion:
At the moment the Slide Interval is fixed for all slides.
It would be a nice-to-have if this could be varied for individual slides.  
Have a default, but if an interval is loaded at the Slide level, use the slide interval.

This would allow for different emphasis to be placed on different adds, or to cater for adds that take longer to view.

We are using the digital sign to display both 'current event' ads and 'values' add - e.g. 'Believe', 'Belong' etc.  It would be nice to have the value adds display quicker.

**Comment by cabal95** [comment]
Sounds like a good idea. It might be a while before I get to this but I'll put it on the todo list.

**Comment by cabal95** [comment]
Will be in release 1.3.0 shortly.
