### ISSUE TITLE
Content Channel Item Status is Not Taken Into Account

### ISSUE THREAD

**Issue by brandon-meeks** [ShepherdDev/digital-signage#7]
When displaying content on a display, the "Status" is not taken into account when displaying the Content Channel Item. Only items with a status of "Approved" should be displayed.

Seems that this line"
`var items = contentChannel.Items.Where( i => i.StartDateTime <= DateTime.Now && ( i.ExpireDateTime == null || i.ExpireDateTime > DateTime.Now ) );`

Could be updated to this:
`var items = contentChannel.Items.Where( i => i.StartDateTime <= DateTime.Now && ( i.ExpireDateTime == null || i.ExpireDateTime > DateTime.Now ) && i.Status == 2 );`

**Comment by cabal95** [comment]
Thanks @brandon-meeks for pointing this out. I'll take a look at it.  Based on the code you pasted it looks like we are also using `DateTime.Now` instead of `RockDateTime.Now` which could cause issues for people in cloud hosted environments so I'll take a look at that too.

**Comment by cabal95** [comment]
This will be fixed in version 1.4.0 of the plugin to be released shortly.
